import type { Role } from '@/features/auth/types/types';
import type { Deal } from '@/features/deals/types/deals.types';
import type { Lead } from '@/features/leads/types';
import { Permission } from '@/utils/rbac/Permission';
import { Contact, Handshake, History, Home, Receipt, Settings, UserPlus, Users, Users2Icon, type LucideIcon } from 'lucide-react';

export interface SidebarLink {
    label: string;
    path: string;
    icon: LucideIcon; // lucide icon component
    roles?: Role[];
    permission: Permission;
}

export interface SidebarGroup {
    title: string;
    links: SidebarLink[];
}

export const navbarLinks: SidebarGroup[] = [
    {
        title: 'Main',
        links: [
            { label: 'Dashboard', path: '/dashboard', icon: Home, permission: Permission.DASHBOARD_READ },
            { label: 'Contacts', path: '/contacts', icon: Contact, permission: Permission.CONTACTS_READ }
    ],
    },
    {
        title: 'Management',
        links: [
            { label: 'Leads', path: '/leads', icon: UserPlus, permission: Permission.LEADS_READ },
            { label: 'Deals', path: '/deals', icon: Handshake, permission: Permission.DEALS_READ },
            { label: 'Orders', path: '/orders', icon: Receipt, permission: Permission.ORDERS_READ },
            { label: 'Customers', path: '/customers', icon: Users, permission: Permission.CUSTOMERS_READ },
            { label: 'Users', path: '/users', icon: Users2Icon, permission: Permission.USERS_READ },
            { label: 'Activity Logs', path: '/activity', icon: History, permission: Permission.ACTIVITY_READ },
            { label: 'Settings', path: '/settings', icon: Settings, permission: Permission.PROFILE_READ },
        ],
    },
];

export const overviewData = [
    {
        name: 'Jan',
        total: 1500,
    },
    {
        name: 'Feb',
        total: 2000,
    },
    {
        name: 'Mar',
        total: 1000,
    },
    {
        name: 'Apr',
        total: 5000,
    },
    {
        name: 'May',
        total: 2000,
    },
    {
        name: 'Jun',
        total: 5900,
    },
    {
        name: 'Jul',
        total: 2000,
    },
    {
        name: 'Aug',
        total: 5500,
    },
    {
        name: 'Sep',
        total: 2000,
    },
    {
        name: 'Oct',
        total: 4000,
    },
    {
        name: 'Nov',
        total: 1500,
    },
    {
        name: 'Dec',
        total: 2500,
    },
];

export const recentSalesData = [
    {
        id: 1,
        name: 'Aysel Mammadova',
        email: 'aysel.mammadova@example.com',
        image: 'https://randomuser.me/api/portraits/women/75.jpg',
        total: 850,
        date: '2025-11-10T10:30:00Z',
        product: 'CRM Premium Plan',
    },
    {
        id: 2,
        name: 'Rashad Aliyev',
        email: 'rashad.aliyev@example.com',
        image: 'https://randomuser.me/api/portraits/men/32.jpg',
        total: 420,
        date: '2025-11-09T14:15:00Z',
        product: 'Email Automation Add-on',
    },
    {
        id: 3,
        name: 'Nigar Huseynova',
        email: 'nigar.huseynova@example.com',
        image: 'https://randomuser.me/api/portraits/women/22.jpg',
        total: 1250,
        date: '2025-11-08T09:20:00Z',
        product: 'Enterprise CRM Suite',
    },
    {
        id: 4,
        name: 'Elvin Karimov',
        email: 'elvin.karimov@example.com',
        image: 'https://randomuser.me/api/portraits/men/47.jpg',
        total: 310,
        date: '2025-11-07T16:45:00Z',
        product: 'Lead Tracker',
    },
    {
        id: 5,
        name: 'Leyla Abbasova',
        email: 'leyla.abbasova@example.com',
        image: 'https://randomuser.me/api/portraits/women/42.jpg',
        total: 560,
        date: '2025-11-06T11:10:00Z',
        product: 'Sales Insights Dashboard',
    },
    {
        id: 6,
        name: 'Murad Safarov',
        email: 'murad.safarov@example.com',
        image: 'https://randomuser.me/api/portraits/men/15.jpg',
        total: 980,
        date: '2025-11-05T13:30:00Z',
        product: 'CRM Team License',
    },
];

export const topProducts = [
    {
        number: 1,
        name: 'Apple MacBook Pro 16” (M3)',
        description: 'Powerful laptop for professionals with Retina display',
        image: 'https://images.unsplash.com/photo-1612831662375-295c1003d3d1?auto=format&fit=crop&w=800&q=60',
        price: 2899,
        status: 'Delivered',
        rating: 4.9,
    },
    {
        number: 2,
        name: 'iPhone 15 Pro Max',
        description: 'Flagship smartphone with A17 Pro chip and titanium frame',
        image: 'https://images.unsplash.com/photo-1695048133260-4bb9dc4a6f46?auto=format&fit=crop&w=800&q=60',
        price: 1399,
        status: 'Delivered',
        rating: 4.8,
    },
    {
        number: 3,
        name: 'Sony WH-1000XM5 Headphones',
        description: 'Noise Cancelling Wireless Bluetooth Over-Ear Headphones',
        image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=800&q=60',
        price: 399,
        status: 'Pending',
        rating: 4.7,
    },
    {
        number: 4,
        name: 'Apple MacBook Air M3 (2025)',
        description: '13-inch Liquid Retina display, 512GB SSD, 16GB RAM',
        image: 'https://images.unsplash.com/photo-1527443154391-507e9dc6c5cc?auto=format&fit=crop&w=800&q=60',
        price: 1699,
        status: 'Delivered',
        rating: 4.9,
    },
    {
        number: 5,
        name: 'GoPro HERO12 Black',
        description: '5.3K60 Ultra HD video, waterproof, stabilization system',
        image: 'https://images.unsplash.com/photo-1581090700227-1e37b190418e?auto=format&fit=crop&w=800&q=60',
        price: 449,
        status: 'In Progress',
        rating: 4.6,
    },
    {
        number: 6,
        name: 'Dell XPS 15',
        description: 'Intel Core i7, 1TB SSD, 32GB RAM, OLED 3.5K Touch Display',
        image: 'https://images.unsplash.com/photo-1593642634315-48f5414c3ad9?auto=format&fit=crop&w=800&q=60',
        price: 2099,
        status: 'Delivered',
        rating: 4.9,
    },
    {
        number: 7,
        name: 'Apple AirPods Pro (2nd Gen)',
        description: 'Active Noise Cancellation, MagSafe Case, USB-C',
        image: 'https://images.unsplash.com/photo-1603791452906-c55f7c4d451c?auto=format&fit=crop&w=800&q=60',
        price: 249,
        status: 'Delivered',
        rating: 4.8,
    },
    {
        number: 8,
        name: 'Logitech MX Mechanical Keyboard',
        description: 'Low-profile tactile switches, Bluetooth & USB-C, backlit keys',
        image: 'https://images.unsplash.com/photo-1593642532973-d31b6557fa68?auto=format&fit=crop&w=800&q=60',
        price: 159,
        status: 'Delivered',
        rating: 4.7,
    },
    {
        number: 9,
        name: 'Sony Alpha a7 IV Mirrorless Camera',
        description: '33MP Full-Frame sensor, 4K60p video, advanced autofocus',
        image: 'https://images.unsplash.com/photo-1600180758897-83b62e36a10e?auto=format&fit=crop&w=800&q=60',
        price: 2499,
        status: 'Pending',
        rating: 4.9,
    },
    {
        number: 10,
        name: 'Apple iPad Pro 12.9” M3',
        description: 'Liquid Retina XDR, 256GB, Wi-Fi + Cellular, Silver',
        image: 'https://images.unsplash.com/photo-1593642634367-d91a135587b5?auto=format&fit=crop&w=800&q=60',
        price: 1399,
        status: 'Cancelled',
        rating: 4.5,
    },
    {
        number: 11,
        name: 'Samsung Galaxy Tab S9',
        description: '11-inch AMOLED, 512GB, 120Hz, stylus support',
        image: 'https://images.unsplash.com/photo-1603791452876-019b0b70f151?auto=format&fit=crop&w=800&q=60',
        price: 899,
        status: 'Delivered',
        rating: 4.7,
    },
    {
        number: 12,
        name: 'Razer Huntsman V3 Keyboard',
        description: 'Optical mechanical keyboard with RGB lighting',
        image: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?auto=format&fit=crop&w=800&q=60',
        price: 199,
        status: 'Delivered',
        rating: 4.8,
    },
    {
        number: 13,
        name: 'DJI Mini 4 Pro Drone',
        description: 'Compact drone with 4K HDR camera and obstacle avoidance',
        image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=800&q=60',
        price: 1099,
        status: 'Pending',
        rating: 4.7,
    },
    {
        number: 14,
        name: 'Fitbit Charge 6',
        description: 'Fitness tracker with heart-rate monitoring and GPS',
        image: 'https://images.unsplash.com/photo-1617188572463-67c5b3b4b18b?auto=format&fit=crop&w=800&q=60',
        price: 179,
        status: 'Delivered',
        rating: 4.6,
    },
];

export const customersData = [
    {
        id: 1,
        name: 'Aysel Mammadova',
        email: 'aysel.mammadova@example.com',
        phone: '+994 50 123 45 67',
        company: 'Tech Solutions LLC',
        position: 'Sales Manager',
        location: 'Baku, Azerbaijan',
        avatar: 'https://randomuser.me/api/portraits/women/75.jpg',
        status: 'Active',
        lastContacted: '2025-11-10',
        notes: 'Interested in premium products, follow up next week.',
    },
    {
        id: 2,
        name: 'Rashad Aliyev',
        email: 'rashad.aliyev@example.com',
        phone: '+994 55 987 65 43',
        company: 'Digital Innovations',
        position: 'CTO',
        location: 'Baku, Azerbaijan',
        avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
        status: 'Active',
        lastContacted: '2025-11-08',
        notes: 'Looking for cloud solutions, schedule demo call.',
    },
    {
        id: 3,
        name: 'Nigar Huseynova',
        email: 'nigar.huseynova@example.com',
        phone: '+994 51 234 56 78',
        company: 'Creative Labs',
        position: 'Marketing Lead',
        location: 'Sumqayit, Azerbaijan',
        avatar: 'https://randomuser.me/api/portraits/women/22.jpg',
        status: 'Inactive',
        lastContacted: '2025-10-30',
        notes: 'Not responsive for now, try after a month.',
    },
    {
        id: 4,
        name: 'Elvin Karimov',
        email: 'elvin.karimov@example.com',
        phone: '+994 70 345 67 89',
        company: 'NextGen Solutions',
        position: 'Product Manager',
        location: 'Ganja, Azerbaijan',
        avatar: 'https://randomuser.me/api/portraits/men/47.jpg',
        status: 'Active',
        lastContacted: '2025-11-09',
        notes: 'Interested in analytics dashboard, sent proposal.',
    },
    {
        id: 5,
        name: 'Leyla Abbasova',
        email: 'leyla.abbasova@example.com',
        phone: '+994 77 567 89 01',
        company: 'Innovatech',
        position: 'CEO',
        location: 'Baku, Azerbaijan',
        avatar: 'https://randomuser.me/api/portraits/women/42.jpg',
        status: 'Active',
        lastContacted: '2025-11-11',
        notes: 'Top client, schedule meeting for product demo.',
    },
    {
        id: 6,
        name: 'Murad Safarov',
        email: 'murad.safarov@example.com',
        phone: '+994 50 678 90 12',
        company: 'CloudWorks',
        position: 'Lead Developer',
        location: 'Baku, Azerbaijan',
        avatar: 'https://randomuser.me/api/portraits/men/15.jpg',
        status: 'Inactive',
        lastContacted: '2025-10-28',
        notes: 'Not interested in current offer, try next quarter.',
    },
    {
        id: 7,
        name: 'Sara Quliyeva',
        email: 'sara.quliyeva@example.com',
        phone: '+994 55 123 45 67',
        company: 'Visionary Tech',
        position: 'Business Analyst',
        location: 'Sumqayit, Azerbaijan',
        avatar: 'https://randomuser.me/api/portraits/women/50.jpg',
        status: 'Active',
        lastContacted: '2025-11-07',
        notes: 'Requested product comparison chart, sent via email.',
    },
    {
        id: 8,
        name: 'Kamran Huseynov',
        email: 'kamran.huseynov@example.com',
        phone: '+994 51 234 56 78',
        company: 'Smart Solutions',
        position: 'Operations Manager',
        location: 'Baku, Azerbaijan',
        avatar: 'https://randomuser.me/api/portraits/men/65.jpg',
        status: 'Active',
        lastContacted: '2025-11-06',
        notes: 'Interested in CRM tools, scheduled call for Monday.',
    },
    {
        id: 9,
        name: 'Amina Rzayeva',
        email: 'amina.rzayeva@example.com',
        phone: '+994 70 345 67 89',
        company: 'Tech Innovators',
        position: 'HR Manager',
        location: 'Ganja, Azerbaijan',
        avatar: 'https://randomuser.me/api/portraits/women/68.jpg',
        status: 'Inactive',
        lastContacted: '2025-10-25',
        notes: 'Currently on vacation, follow up in December.',
    },
    {
        id: 10,
        name: 'Tural Mammadli',
        email: 'tural.mammadli@example.com',
        phone: '+994 77 567 89 01',
        company: 'NextLevel Tech',
        position: 'Software Engineer',
        location: 'Baku, Azerbaijan',
        avatar: 'https://randomuser.me/api/portraits/men/72.jpg',
        status: 'Active',
        lastContacted: '2025-11-10',
        notes: 'Interested in automation tools, demo scheduled.',
    },
];

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.j@techcorp.com',
    phone: '+1 (555) 123-4567',
    company: 'TechCorp Inc',
    status: 'qualified',
    value: 45000,
    source: 'Website',
    assignedTo: 'John Smith',
    createdAt: '2025-11-20',
    lastContact: '2025-11-27'
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'm.chen@innovate.io',
    phone: '+1 (555) 234-5678',
    company: 'Innovate Solutions',
    status: 'negotiation',
    value: 78000,
    source: 'Referral',
    assignedTo: 'Emma Wilson',
    createdAt: '2025-11-18',
    lastContact: '2025-11-28'
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'e.rodriguez@startup.com',
    phone: '+1 (555) 345-6789',
    company: 'Startup Labs',
    status: 'new',
    value: 32000,
    source: 'LinkedIn',
    assignedTo: 'John Smith',
    createdAt: '2025-11-28',
    lastContact: '2025-11-28'
  },
  {
    id: '4',
    name: 'David Thompson',
    email: 'david.t@megacorp.com',
    phone: '+1 (555) 456-7890',
    company: 'MegaCorp Ltd',
    status: 'contacted',
    value: 125000,
    source: 'Trade Show',
    assignedTo: 'Emma Wilson',
    createdAt: '2025-11-25',
    lastContact: '2025-11-26'
  },
  {
    id: '5',
    name: 'Lisa Anderson',
    email: 'l.anderson@biztech.net',
    phone: '+1 (555) 567-8901',
    company: 'BizTech Partners',
    status: 'qualified',
    value: 56000,
    source: 'Cold Call',
    assignedTo: 'John Smith',
    createdAt: '2025-11-22',
    lastContact: '2025-11-27'
  },
  {
    id: '6',
    name: 'Robert Kim',
    email: 'r.kim@digitalco.com',
    phone: '+1 (555) 678-9012',
    company: 'Digital Co',
    status: 'lost',
    value: 23000,
    source: 'Website',
    assignedTo: 'Emma Wilson',
    createdAt: '2025-11-15',
    lastContact: '2025-11-24'
  },
  {
    id: '7',
    name: 'Amanda White',
    email: 'a.white@future.io',
    phone: '+1 (555) 789-0123',
    company: 'Future Systems',
    status: 'new',
    value: 67000,
    source: 'Email Campaign',
    assignedTo: 'John Smith',
    createdAt: '2025-11-27',
    lastContact: '2025-11-27'
  },
  {
    id: '8',
    name: 'James Martinez',
    email: 'j.martinez@growth.com',
    phone: '+1 (555) 890-1234',
    company: 'Growth Ventures',
    status: 'negotiation',
    value: 95000,
    source: 'Referral',
    assignedTo: 'Emma Wilson',
    createdAt: '2025-11-19',
    lastContact: '2025-11-28'
  }
];

export const mockDeals: Deal[] = [
  { id: "1", name: "Enterprise SaaS License", customer: "Acme Corp", amount: 125000, status: "Negotiation", expectedClose: "2024-12-15" },
  { id: "2", name: "Cloud Infrastructure", customer: "TechStart Inc", amount: 85000, status: "New", expectedClose: "2024-12-20" },
  { id: "3", name: "Annual Support Contract", customer: "Global Solutions", amount: 45000, status: "Won", expectedClose: "2024-11-30" },
  { id: "4", name: "Platform Migration", customer: "DataFlow Systems", amount: 200000, status: "Negotiation", expectedClose: "2025-01-10" },
  { id: "5", name: "Consulting Services", customer: "Innovation Labs", amount: 30000, status: "Lost", expectedClose: "2024-11-15" },
];